version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive

  settings:
    revive:
      rules:
        - name: exported
          severity: warning

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: testdata/
      linters:
        - revive
